### ISSUE TITLE
[BUG} NoGap slows down the browser / [Questions]

### ISSUE THREAD

**Issue by allecsc** [JustAdumbPrsn/Zen-Nebula#179]
Hi, I've noticed that my Zen has become a lot slower recently and after digging around a little I found out that NoGaps mod was the issue which makes sense because I've only enabled it recently. 
<details>
<summary>Bug</summary>

https://github.com/user-attachments/assets/401a6418-dfd8-4850-bc0d-dd5c3dac5f4c
</details>

I've managed to fix it by changing the backdrop-filter and selector. It seems to look the same and work as intended now. Could you check if it works for you too?

<details>
<summary>NoGaps Fix</summary>

```css
/* ---------------------- NOGAPS MOD ------------------------ */
  
  @media (-moz-pref("nebula-nogaps-mod")) {
    /* Simplified selector to avoid expensive :has() */
    [zen-single-toolbar="true"] {
      
      #zen-appcontent-wrapper {
        position: relative;
      }
  
      #zen-appcontent-navbar-wrapper {
        position: absolute;
        width: 100% !important;
        height: 50px;
        /* Reduced blur for better performance */
        backdrop-filter: blur(10px);
        background: var(--zen-main-browser-background) !important;
        border-bottom: 1.7px solid light-dark(rgba(0, 0, 0, 0.2), rgba(255, 255, 255, 0.1));
      }
  
      #zen-tabbox-wrapper {
        margin: 0 !important;
      }
  
      .browserSidebarContainer {
        border-radius: 0.1px !important;
        box-shadow: none !important;
      }
    }
  }
  
  /* ----------------- NOGAPS COMPACT MOD ----------------- */
  
  @media (-moz-bool-pref: "nebula-nogaps-compact-mod") {
    :root[zen-compact-mode="true"]:not([customizing]) {
        /* Simplified selector */
        #zen-appcontent-wrapper {
            margin: 0 !important;
  
            #zen-tabbox-wrapper {
                margin: 0 !important;
            }
  
            #zen-tabbox-wrapper .browserSidebarContainer,
            #zen-tabbox-wrapper browser {
                margin: 0 !important;
                border-radius: 0 !important;
            }
        }
    }
    
    /* Separate media query to avoid nesting */
    @media (-moz-bool-pref: "zen.view.use-single-toolbar") {
      :root[zen-compact-mode="true"]:not([customizing]) #zen-appcontent-wrapper {
          position: relative;
      }

      :root[zen-compact-mode="true"]:not([customizing]) #zen-appcontent-navbar-wrapper {
        position: absolute;
        width: 100% !important;
        height: 50px; /* Optional: thicker navbar */
        /* Reduced blur for better performance */
        backdrop-filter: blur(10px);
        background: var(--zen-main-browser-background) !important;
        border-bottom: 1.7px solid light-dark(rgba(0, 0, 0, 0.2), rgba(255, 255, 255, 0.1));
      }
    }
  }
``` 
</details>

On another note, I’ve been meaning to ask you a few things about Nebula since you made the switch to Sine. I usually like to tinker, and I had no trouble editing Nebula before v3.0, but since I installed it through Sine, I can’t add or change Nebula-specific stuff through an usual css file anymore. I used to have a *Nebula_override.css* with all my changes, but now I'm forced to add them directly to Nebula's *userChrome.css* and I'm worried they might get overwritten once you push a new update. Even more so, I like having the red gradient of the close button on the right side of the tab, under the **X**, and that used to be a simple fix before by changing the direction of the *linear-gradient* background, but now, overriding it from **any** other file, including Nebula's files, doesn’t seem to work anymore. The only way I’ve managed to fix it is by editing *Tabstyles.css* directly, which obviously isn’t ideal long-term. Can you please check if the same thing happens on your end?

Also, I’ve just released a custom theme built on top of your already amazing Nebula, and first of all, I hope that’s okay with you. Let me know if it's not. CosmoCreeper also suggested using Sine's auto-install feature to bundle Nebula when installing Altover, my theme, to streamline the setup process. But since I currently have to overwrite some of your files to make it work, I don’t think I can pack it as a proper standalone mod for Sine. Any chance you could look into it and see if there’s a cleaner way to make this all work?

Let me know what you think! Thanks.

**Comment by JustAdumbPrsn** [comment]
@allecsc you can still easily edit nebula theme, in browser toolbox, just search for specific nebula modules and edit them as you wish, and if you really not want to edit it from there then just download nebula through the manual process, and the slowness you are talking about while using nogaps, i dont encounter any such thing and so far tbh no one else has reported this issue
and also i noticed that your nogaps doesnt seem to work for some reason? so this might have to do with other mods???

**Comment by allecsc** [comment]
That's really weird. Well if no one else has that issue it's ok then. For me it works with that fix and that is the only thing that makes it happen.

About the editing, of course I can do that but the point is I can't save them separately from your mod, which would get overwrite in case of an update, I believe. Now I don't know if that's a limitation of Sine, but with regular mods I can easily overwrite them from another css file. I'd like to make it easier for people that want to try my theme mostly, and save me some time when you add new features, cuz I really don't want to miss any good stuff you put out there. 😆

<details>

<summary> Here's the animation for the URLbar you asked about </summary>

```css
/* ------------------- NATSUMI STYLE URLBAR ANIMATION -------------------- */

#urlbar[open] #urlbar-background {
  background: light-dark(rgba(255, 255, 255, 0.4), rgba(0, 0, 0, 0.6)) !important;
}

/* Animation Variables - Faster timings */
:root {
  --urlbar-appear-animation-duration: 0.20s;  /* Faster URLbar appear */
  --urlbar-results-animation-duration: 0.5s;  /* Faster results appear */
  --urlbar-individual-result-animation-duration: 0.6s;  /* Faster individual results */
  --urlbar-individual-result-animation-delay: 0.06s;  /* Shorter delay between items */
  --urlbar-individual-result-animation-delay-offset: 0.1s;  /* Shorter initial delay */
  --urlbar-individual-result-expand-size: 1.05;  /* Slightly reduced scale */
  --animation-duration-subtle: 0.3s;  /* Faster subtle animation */
  --expand-width: var(--urlbar-individual-result-expand-size, 1.05);
}

/* Keyframe Definitions */
@keyframes urlbar-appear {
  0% { margin-top: -25vh; }
  100% { margin-top: 0; }
}

@keyframes urlbar-appear-sideways {
  0% { margin-left: calc(-50% + calc(min(90%, 60rem) / 2)); }
  100% { margin-left: 0; }
}

@keyframes individual-result-appear {
  0% {
    opacity: 0;
    transform: scale(0.95);
    background: color-mix(in srgb, var(--natsumi-colors-tertiary) 30%, transparent);
    filter: blur(10px);
  }
  40% {
    opacity: 1;
  }
  60% {
    opacity: 1;
    transform: scale(var(--expand-width));
    background: color-mix(in srgb, var(--natsumi-primary-color) 15%, transparent);
    filter: blur(0);
  }
  100% {
    opacity: 1;
    transform: scale(1);
    background: transparent;
  }
}

@keyframes individual-result-appear-subtle {
  0% {
    opacity: 1;
    transform: scale(1);
    background: transparent;
  }
  60% {
    transform: scale(1.02);
    background: color-mix(in srgb, var(--natsumi-primary-color) 10%, transparent);
  }
  100% {
    opacity: 1;
    transform: scale(1);
    background: transparent;
  }
}

@keyframes pinned-icon-appear {
  0% { opacity: 0; transform: scale(0.8); }
  40% { opacity: 1; }
  60% { opacity: 1; transform: scale(1.05); }
  100% { opacity: 1; transform: scale(1); }
}

@keyframes urlbar-gradient {
  0% { background-position: 0% 50%; }
  100% { background-position: 300% 50%; }
}

/* Animation Triggers */
#urlbar[breakout-extend] {
  animation-name: urlbar-appear;
  animation-duration: var(--urlbar-appear-animation-duration);
  animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1);  /* Smoother easing */
}

#urlbar[breakout-extend][zen-floating-urlbar="true"] {
  animation-name: urlbar-appear-sideways;
  animation-duration: var(--urlbar-appear-animation-duration);
  animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
}

#urlbar-results .urlbarView-row {
  animation-name: individual-result-appear;
  animation-duration: var(--urlbar-individual-result-animation-duration);
  animation-fill-mode: forwards;
  animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  opacity: 0;
}

#urlbar-results .urlbarView-row .urlbarView-type-icon {
  animation-name: pinned-icon-appear;
  animation-duration: 0.3s;
  animation-fill-mode: forwards;
  animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  opacity: 0;
}

/* Individual result delays */
#urlbar-results .urlbarView-row:nth-child(1) {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 0) + var(--urlbar-individual-result-animation-delay-offset));
}

#urlbar-results .urlbarView-row:nth-child(2) {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 1) + var(--urlbar-individual-result-animation-delay-offset));
}

#urlbar-results .urlbarView-row:nth-child(3) {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 2) + var(--urlbar-individual-result-animation-delay-offset));
}

#urlbar-results .urlbarView-row:nth-child(4) {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 3) + var(--urlbar-individual-result-animation-delay-offset));
}

#urlbar-results .urlbarView-row:nth-child(5) {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 4) + var(--urlbar-individual-result-animation-delay-offset));
}
/*
#urlbar-results .urlbarView-row:nth-child(6) {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 5) + var(--urlbar-individual-result-animation-delay-offset));
}

#urlbar-results .urlbarView-row:nth-child(7) {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 6) + var(--urlbar-individual-result-animation-delay-offset));
}

/* Icon delays */
#urlbar-results .urlbarView-row:nth-child(1) .urlbarView-type-icon {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 0) + var(--urlbar-individual-result-animation-delay-offset) + var(--urlbar-individual-result-animation-duration));
}

#urlbar-results .urlbarView-row:nth-child(2) .urlbarView-type-icon {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 1) + var(--urlbar-individual-result-animation-delay-offset) + var(--urlbar-individual-result-animation-duration));
}

#urlbar-results .urlbarView-row:nth-child(3) .urlbarView-type-icon {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 2) + var(--urlbar-individual-result-animation-delay-offset) + var(--urlbar-individual-result-animation-duration));
}

#urlbar-results .urlbarView-row:nth-child(4) .urlbarView-type-icon {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 3) + var(--urlbar-individual-result-animation-delay-offset) + var(--urlbar-individual-result-animation-duration));
}

#urlbar-results .urlbarView-row:nth-child(5) .urlbarView-type-icon {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 4) + var(--urlbar-individual-result-animation-delay-offset) + var(--urlbar-individual-result-animation-duration));
}
/*
#urlbar-results .urlbarView-row:nth-child(6) .urlbarView-type-icon {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 5) + var(--urlbar-individual-result-animation-delay-offset) + var(--urlbar-individual-result-animation-duration));
}

#urlbar-results .urlbarView-row:nth-child(7) .urlbarView-type-icon {
  animation-delay: calc((var(--urlbar-individual-result-animation-delay) * 6) + var(--urlbar-individual-result-animation-delay-offset) + var(--urlbar-individual-result-animation-duration));
}

``` 

</details>


You can find all of my other changes [here](https://github.com/allecsc/Altover/blob/main/ALTOVER/chrome/zen-themes/Nebula/userChrome.css) and [here](https://github.com/allecsc/Altover/blob/main/ALTOVER/chrome/Altover.css).
